### ISSUE TITLE
Possible solution for issue with Unicode strings

### ISSUE THREAD

**Issue by remorse** [lokku/Text-Hogan#3]
Hi! As you note in the documentation, `Text::Hogan::Compiler` is _very_ slow when dealing with Unicode ("character") strings. I mentioned this at the Boston Perl Mongers meeting last night, and Jerrad Pierce (JPIERCE on PAUSE) made a throw-away comment that you should just split on `//`, and then work with the array. This got me to thinking, and I wondered how hard it would be, and if it would work.

I'm interested in this because my templates include translations into languages like Bengali and Arabic, and handling Unicode strings makes compiling a template take _much_ longer (1 minute vs 1 second, approx). But changing everything to byte strings gets awkward, and involves problems with double-encoding strings, etc.

I spent a few minutes trying it out, and it worked with very few changes. The code could be made better, as right now there is still some places where it needs to work with the string, but I did get it to pass all of the spec tests, and when I subbed it into my code for the existing version, and got rid of all the calls to `encode` that get rid of Unicode strings, it worked, and started up in roughly the same length as with non-Unicode strings.

I've put it in my fork as the "array-vs-string" branch -- do you think this would be useful?

Thanks,
Ricky

**Comment by freyfogle** [comment]
wow @remorse that sounds fantastic, would love to try it out

**Comment by kaoru** [comment]
Amazing @remorse! Can you whip up a quick test with [Dumbbench](https://metacpan.org/pod/Dumbbench) to prove it's faster? If so you should update the POD to remove the note about unicode/character strings being slow :grinning: 

I guess the next step is to make the array of characters approach more consistent so that the else in `char_at` can be removed?

I'm leaving on a 2 week trip tomorrow evening so I'm probably going to be radio silent until the beginning of April I'm afraid. If I come back and find you've finished this I will be more than happy to merge it!

Thanks also for mentioning Text::Hogan at the Boston.pm meeting! Very cool :+1:

**Comment by jonassmedegaard** [comment]
Just an uneducated remark: You might want to consider using Unicode::UTF8

**Comment by kaoru** [comment]
@jonassmedegaard I don't think that would help, it looks like the only thing that the Unicode::UTF8 module provides above the default UTF8 handling provided by the Encode core module is the ability to provide a fallback code reference that gets called when an ill-formed sequence is encountered.

As described in [the Text::Hogan::Compiler docs](https://metacpan.org/pod/Text::Hogan::Compiler#ENCODING), if you want to use Text::Hogan with Perl character strings (as opposed to byte strings) you must decode your template byte strings into character strings before passing them into the Compiler or the render method arguments.

```
#!/usr/bin/env perl

use 5.20.0;
use strict;
use warnings;

# The bits of utf8::all we need to make sure the strings below are character
# strings not byte strings, and STDOUT is expecting character strings for the
# say at the end :)
use utf8;
use feature qw(unicode_strings fc unicode_eval);
binmode STDOUT, ':encoding(utf-8)';

use Text::Hogan::Compiler;

my $compiler = Text::Hogan::Compiler->new;

my $text = "こんにちは、{{name}}!";

my $tokens   = $compiler->scan($text);
my $tree     = $compiler->parse($tokens, $text);
my $template = $compiler->generate($tree, $text);

say $template->render({ name => "アレックス" });
```

Or you can use byte strings end to end...

```
#!/usr/bin/env perl

use 5.20.0;
use strict;
use warnings;

# UTF-8 byte srings!
use utf8;
use bytes;

use Text::Hogan::Compiler;
 
my $compiler = Text::Hogan::Compiler->new;
 
my $text = "こんにちは、{{name}}!";
 
my $tokens   = $compiler->scan($text);
my $tree     = $compiler->parse($tokens, $text);
my $template = $compiler->generate($tree, $text);
 
say $template->render({ name => "アレックス" });
```

Bytes are faster, but character strings have ***much better*** support for string manipulation such as splitting safely, sorting lists of strings, counting the length of strings, etc.

---------------

I think @remorse's suggestion of splitting the template string into an array immediately and then working with that array would be a performance improvement - in some extreme cases a huge improvement - because the current way we do it with the [char_at](https://github.com/kaoru/Text-Hogan/blob/8f561c471855fd2314ac32d3f80898cbfd07e419/lib/Text/Hogan/Compiler.pm#L402) method is effectively splitting the string on characters every time it's called. Doing that once instead of 1000s of times would be great :+1:

**Comment by jonassmedegaard** [comment]
Quoting Alex Balhatchet (2019-02-24 00:21:20)
> @jonassmedegaard I don't think that would help, it looks like the only thing that the Unicode::UTF8 module provides above the default UTF8 handling provided by the Encode core module is the ability to provide a fallback code reference that gets called when an ill-formed sequence is encountered.

As I wrote, my suggestion was uneducated.

[ details snipped ]

Thanks a lot for educating me! :-)


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by remorse** [comment]
Hi! I'm sorry that I haven't gotten to the benchmark you were talking about before. You made the request, then something came up, and then other things happened, etc.

The comment recently reminded me about this, so I set out to try and get the benchmark you wanted.

It took me some time to get a good sample, because anything small doesn't really show an improvement (and may even show a slight degradation). However, for larger text there is a real improvement.

I generated a 23K HTML file which is mostly in Arabic for the text, and has a bunch of markup in it as well. I then ran the following program under Dumbbench:

```
#!/usr/bin/env perl
use Modern::Perl '2017';
use lib './Text-Hogan/lib';
use Text::Hogan::Compiler;
use Path::Tiny;

my $compiler = Text::Hogan::Compiler->new();
my $text     = path('./ar.html')->slurp_utf8();
my $template = $compiler->compile( $text, { 'delimiters' => "<?ts ?>", 'allow_whitespace_before_hashmark' => 1 } );
```

If I used the existing `Text::Hogan` version (1.09), I got:

```
buxtehude:git rem16$ dumbbench -p 0.005 -- perl ./test-text-hogan.pl
cmd: Ran 20 iterations (0 outliers).
cmd: Rounded run time per iteration: 4.022e+00 +/- 1.1e-02 (0.3%)
```

If I used the altered version (I applied my previous patch to 1.09), I got:

```
buxtehude:git rem16$ dumbbench -p 0.005 -- perl ./test-text-hogan.pl
cmd: Ran 21 iterations (1 outliers).
cmd: Rounded run time per iteration: 7.793e-02 +/- 3.2e-04 (0.4%)
```

This looks like 4 seconds per iteration for the string based version, vs. approx 0.07 secs for the array based version.

I don't know what this does to memory usage, though.

**Comment by kaoru** [comment]
@remorse I just tried reproducing your result myself using the same script. I created my own 20KB file mostly containing Japanese with a bit of mustache syntax added for effect, and I added a SHA1 output to your script to make sure that we got exactly the same output on both branches.

**v1.09** f0aa691

```
$ dumbbench -p 0.005 -- perl ./bench.pl
7a8ed1b9fb00d8feafc113939e3c58c0f2055899
7a8ed1b9fb00d8feafc113939e3c58c0f2055899
... 20 more of these ...
7a8ed1b9fb00d8feafc113939e3c58c0f2055899
cmd: Ran 20 iterations (0 outliers).
cmd: Rounded run time per iteration: 1.3462e+00 +/- 4.2e-03 (0.3%)
```

**+ your changes** (cherry-picked 01ec500f487ac927c20ed6b93382547f68640929 on top of v1.09)

```
$ dumbbench -p 0.005 -- perl ./bench.pl
7a8ed1b9fb00d8feafc113939e3c58c0f2055899
7a8ed1b9fb00d8feafc113939e3c58c0f2055899
... 20 more of these ...
7a8ed1b9fb00d8feafc113939e3c58c0f2055899
cmd: Ran 25 iterations (5 outliers).
cmd: Rounded run time per iteration: 4.812e-01 +/- 1.0e-03 (0.2%)
```

3 times faster with one compile and one render. Amazing result! :tada: 

I'm going to merge this and release it as 2.00 :rocket:

**Comment by remorse** [comment]
Great! Could you attribute the idea to Jarred please?

**Comment by kaoru** [comment]
Ah you're right, thanks for the reminder @remorse, I'll update the docs again
